#!/bin/sh
# By Guillaume Seigneuret 2012
# Start, Stop, Check, Reload GDS


GDS=/cygdrive/d/W3/SCRIPTS/Git-Deployer/GDS.pl
PIDFILE=/var/run/gds.pid
LOGFILE=/var/log/gds.log

gds_start()
{
	echo -n "Starting Git Deployment Server ... "
	$GDS $PIDFILE >> $LOGFILE 2>&1 &
	echo "[STARTED]"
}

gds_stop()
{
	echo -n "Stoping Git Deployment Server ... "
	kill `cat $PIDFILE`
	rm $PIDFILE
	echo "[STOPED]"
}

gds_restart()
{
	gds_stop
	gds_start
}



gds_$1
